#!/bin/sh
#
# SPDX-License-Identifier: MIT
#
set -eu
if [ -f "$D${sysconfdir}/man_db.conf" ]; then
    # Create a temporary man_db.conf with paths to the rootfs, as mandb needs absolute paths
    CONFIG=$(mktemp --tmpdir update-mandb.XXXXX)
    sed "s:\(\s\)/:\1$D/:g" $D${sysconfdir}/man_db.conf > $CONFIG
    mkdir -p $D${localstatedir}/cache/man/
    PSEUDO_UNLOAD=1 ${binprefix}qemuwrapper -L $D $D${bindir}/mandb --config-file $CONFIG --create
    rm -f $CONFIG
    chown -R man:man $D${localstatedir}/cache/man/
else
    echo "man_db.conf not present, skipping mandb update (man-db not installed in this image)"
fi
